name: Predictor

on:
  schedule:
    - cron: '28 18 * * *' # Everyday @ 11:58 PM IST (06:28 PM UTC)

jobs:
  notify:
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Predict & Notify
        run: npm run predict
        env:
          MESSAGE_API_TOKEN: ${{ secrets.MESSAGE_API_TOKEN }}
          MESSAGE_CHANNEL: ${{ vars.MESSAGE_CHANNEL }}
