name: Watcher

on:
  schedule:
    - cron: '30 7 * * *' # Everyday @ 01:00 PM IST (07:30 AM UTC)

jobs:
  notify:
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Watch & Notify
        run: npm run watch
        env:
          MESSAGE_API_TOKEN: ${{ secrets.MESSAGE_API_TOKEN }}
          MESSAGE_CHANNEL: ${{ vars.MESSAGE_CHANNEL }}
